package application;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import javafx.scene.control.ToggleGroup;

import javafx.event.ActionEvent;

import javafx.scene.control.RadioButton;

public class FormCreaPartitaController {
	@FXML
	private TextField txtCodice;
	@FXML
	private RadioButton rdbGiocatori2;
	@FXML
	private ToggleGroup numeroGiocatori;
	@FXML
	private RadioButton rdbGiocatori3;
	@FXML
	private RadioButton rdbGiocatori4;
	@FXML
	private RadioButton rdbGiocatori5;

	// Event Listener on Button.onAction
	@FXML
	public void btnAvanti(ActionEvent event) {
		// TODO Autogenerated
	}
}
