package application;

import javafx.fxml.FXML;

import javafx.fxml.Initializable;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;

import classi.Alert_cambiaForm;
import classi.Gare;
import classi.Gara;
import classi.Giocatore;
import classi.Salvataggio;
import javafx.scene.control.Button;
import javafx.beans.value.ChangeListener;
import javafx.beans.value.ObservableValue;
import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

import javafx.scene.control.TextArea;

import javafx.scene.input.MouseEvent;

public class FormEliminaEventoController implements Initializable{
	Gare g = new Gare();
	@FXML
	private ListView<String> lblPartite = new ListView<>();
	@FXML
	private TextArea txtInfo;
	@FXML
	private Button btnElimina;
	Alert_cambiaForm alert = new Alert_cambiaForm();
	// Event Listener on Button[#btnElimina].onAction
	@FXML
	public void elimina(ActionEvent event) throws IOException{
		//accedo alla gara con il codice selezionato sulla listview
		Gara gara = g.getGara(lblPartite.getSelectionModel().getSelectedItem());
		Salvataggio s = new Salvataggio(gara);
		//chiedo conferma di cancellazione
		if(alert.chiediConferma("Sei sicuro di voler eliminare l'evento avente codice '"+gara.getCodiceGara()+"' ?", "CONFERMA DI ELIMINAZIONE")) {
			if(gara.getCodiceGara().charAt(0) == 'p')
				s.deleteDirectory("partite");
			else
				s.deleteDirectory("tornei");
			alert.mostraInformazione("Eliminazione dell'evento '"+gara.getCodiceGara()+"' avvenuta con successo.", "ELIMINAZIONE ESEGUITA CON SUCCESSO");
			alert.passaAlForm("/application/FormModalitaAdminMenu.fxml", event);
		}
	}
	// Event Listener on ImageView.onMouseClicked
	@FXML
	public void tornaIndietro(MouseEvent event) throws IOException {
		// TODO Autogenerated
		alert.passaAlForm("/application/FormModalitaAdminMenu.fxml",event);
	}
	@FXML
	public void cliccaGara(MouseEvent event) throws FileNotFoundException{
		//accedo alla gara con il codice selezionato sulla listview
		Gara gara = g.getGara(lblPartite.getSelectionModel().getSelectedItem());
		String codice = gara.getCodiceGara();
		String info = "";
		//salvo le info della partita selezionata
		if(codice.charAt(0) == 'p') {
			info = "Codice partita: "+codice+"\n"
					+ "Numero giocatori: "+gara.getGiocatori().length+"\n\n";
			for(Giocatore p: gara.getGiocatori()) {
				info += "Giocatore "+p.getAlias()+"\n Punteggio: "+p.getPunteggio()+"\n Mano: "+p.getMano().toString()+"\n\n";
			}
		}else {
			
		}
		txtInfo.setText(info);
		btnElimina.setVisible(true);
	}
	@Override
	public void initialize(URL arg0, ResourceBundle arg1) {
		for(Gara gara : g.getGare()) {
			lblPartite.getItems().add(gara.getCodiceGara());
		}
	}
}
