package application;

import javafx.fxml.FXML;
import java.io.IOException;
import javafx.event.ActionEvent;
import classi.Alert_cambiaForm;

public class FormPrincipaleController 
{
	Alert_cambiaForm alert = new Alert_cambiaForm();
	@FXML
	public void btnVisualizzaLeaderboard(ActionEvent event) throws IOException
	{
		// TODO Autogenerated
		alert.passaAlForm("/application/FormLeaderboard.fxml",event);
	}

	@FXML
	public void btnModalitaAmministratore(ActionEvent event) throws IOException
	{
		alert.passaAlForm("/application/FormModalitaAmministratore.fxml",event);
	}

	@FXML
	public void btnModalitaGiocatore(ActionEvent event) throws IOException 
	{
		alert.passaAlForm("/application/FormModalitaGiocatore.fxml",event);
	}
}