package application;

import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.event.ActionEvent;
import javafx.scene.control.ListView;
import javafx.scene.input.MouseEvent;
import javafx.scene.control.CheckBox;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.scene.Parent;
import javafx.scene.control.ToggleGroup;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.stage.Modality;
import javafx.stage.Stage;
import java.io.*;
import classi.Salvataggio;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.ResourceBundle;
import com.sun.tools.javac.Main;
import javafx.scene.input.MouseEvent;
import javafx.beans.value.ChangeListener;
import javafx.beans.value.ObservableValue;
import javafx.event.ActionEvent;
import javafx.scene.control.Alert;
import javafx.scene.control.RadioButton;
import javafx.scene.control.TextArea;
import classi.Alert_cambiaForm;
import classi.Giocatore;
import classi.Partita;
import classi.Gara;
import classi.Gare;
import classi.Leaderboard;

public class FormCreaGiocatoreController 
{
	@FXML
	private CheckBox chbRobot;
	@FXML
	private TextField txtAlias;
	@FXML
	private Button btnAggiungiGiocatore = new Button();
	@FXML
	private ListView<String> txtGiocatoriInseriti = new ListView<String>();

	private ArrayList<Giocatore> giocatori = new ArrayList<>();
	private Alert_cambiaForm alert = new Alert_cambiaForm();
	
	@FXML
	public void btnVaiIndietro1(MouseEvent event) throws IOException
	{
		giocatori.clear();
		alert.passaAlForm("/application/FormModalitaAdminMenu.fxml",event);	
		}
	
	@FXML
	public void btnAggiungiGiocatore(ActionEvent event) 
	{
		// TODO Autogenerated
	}

	@FXML
	public void eliminaGiocatore(MouseEvent event) throws IOException
	{
		int indiceEliminato = txtGiocatoriInseriti.getSelectionModel().getSelectedIndex();
		if(indiceEliminato != -1) 
		{
			String alias  =txtGiocatoriInseriti.getSelectionModel().getSelectedItem();
			if(alert.chiediConferma("Sei sicuro di voler eliminare il giocatore di nome: "+alias, "MESSAGGIO DI CONFERMA"))
			{
				giocatori.remove(indiceEliminato);
				txtGiocatoriInseriti.getItems().clear();
				txtGiocatoriInseriti.getItems().addAll(nomiGiocatori());
			}
		}
	}
	
	public String[] nomiGiocatori() 
	{
		String[] g = new String[giocatori.size()];
		for(int i = 0; i < g.length; i++) 
		{
			g[i] = giocatori.get(i).getAlias();
		}
		return g;
	}
}