package application;

import javafx.fxml.FXML;

import java.io.IOException;

import classi.Alert_cambiaForm;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.ListView;

import javafx.scene.control.TextArea;

import javafx.scene.input.MouseEvent;

public class FormEliminaEventoController {
	@FXML
	private ListView lblPartite;
	@FXML
	private TextArea txtInfo;
	@FXML
	private Button btnElimina;
	Alert_cambiaForm alert = new Alert_cambiaForm();
	// Event Listener on Button[#btnElimina].onAction
	@FXML
	public void elimina(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ImageView.onMouseClicked
	@FXML
	public void tornaIndietro(MouseEvent event) throws IOException {
		// TODO Autogenerated
		alert.passaAlForm("/application/FormModalitaAdminMenu.fxml",event);
	}
}
