package application;

import javafx.fxml.FXML;

import javafx.fxml.FXMLLoader;
import java.io.IOException;

import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.stage.Stage;
import javafx.stage.WindowEvent;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.Node;
import classi.Alert_cambiaForm;
import classi.Gara;
import classi.Gare;
public class FormPrincipaleController
{
	Alert_cambiaForm alert = new Alert_cambiaForm();
	@FXML
	public void btnVisualizzaLeaderboard(ActionEvent event) throws IOException
	{
		// TODO Autogenerated
		alert.passaAlForm("/application/FormLeaderboard.fxml",event);
	}

	@FXML
	public void btnModalitaAmministratore(ActionEvent event) throws IOException
	{
		alert.passaAlForm("/application/FormModalitaAmministratore.fxml",event);
	}

	@FXML
	public void btnModalitaGiocatore(ActionEvent event) throws IOException 
	{
		alert.passaAlForm("/application/FormModalitaGiocatore.fxml",event);
	}
	@FXML
	Button button = new Button();
	@FXML
	public void closeButton(ActionEvent event) throws IOException
	{
		Stage stage = (Stage)((Node)event.getSource()).getScene().getWindow();
		if(alert.chiediConferma("Sei sicuro di voler chiudere il gioco?","MESSAGGIO DI CONFERMA"))
			stage.close();
	}
}
