package application;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import javafx.scene.control.ToggleGroup;

import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;

import javafx.scene.control.RadioButton;

public class FormCreaTorneoController {
	@FXML
	private AnchorPane rdbGiocatori4;
	@FXML
	private TextField txtCodice;
	@FXML
	private RadioButton rdbGiocatori2;
	@FXML
	private ToggleGroup numGiocatori;
	@FXML
	private RadioButton rdbGiocatori8;
	@FXML
	private RadioButton rdbGiocatori16;

	// Event Listener on Button.onAction
	@FXML
	public void btnAvanti(ActionEvent event) {
		// TODO Autogenerated
	}
}
