package application;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.event.ActionEvent;

import javafx.scene.image.ImageView;
import javafx.fxml.Initializable;

import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.URL;
import java.util.ResourceBundle;
import java.util.Scanner;

import classi.Carta;
import classi.Gara;
import classi.Gare;
import classi.Giocatore;
import classi.Mazzo;
import classi.Partita;

import java.io.IOException; 

public class FormRigoreController implements Initializable
{
	Gare g = new Gare();
	String turno;
	int posizioneGiocatoreAttaccante;
	int posizioneGiocatoreDifensore;
	String nomeCarta;
	
	Gara partita;
	Mazzo mazzo;
	Giocatore[] players;
	Carta cartaGiocata;
	@FXML
	private ImageView imgPortiere;
	@FXML
	private ImageView imgPallone;
	
	static String codicePartita;
	
	public void copiaCodice(String codice) 
	{
		codicePartita = codice;
	}

	// Event Listener on Button.onAction
	@FXML
	public void btnSinistra(ActionEvent event) 
	{
		// TODO Autogenerated
		if(turno.equals("a")) {
			cartaGiocata = Carta.RIGORE_SX;
		}else {
			cartaGiocata = Carta.PORTIERE_SX;
			rigoreSegnato(Carta.valueOf(nomeCarta), cartaGiocata);
		}
	}
	// Event Listener on Button.onAction
	@FXML
	public void btnCentro(ActionEvent event) 
	{
		// TODO Autogenerated
		if(turno.equals("a")) {
			cartaGiocata = Carta.RIGORE_C;
		}else {
			cartaGiocata = Carta.PORTIERE_C;
			rigoreSegnato(Carta.valueOf(nomeCarta), cartaGiocata);
		}
	}
	// Event Listener on Button.onAction
	@FXML
	public void btnDestra(ActionEvent event) 
	{
		// TODO Autogenerated
		if(turno.equals("a")) {
			cartaGiocata = Carta.RIGORE_DX;
		}else {
			cartaGiocata = Carta.PORTIERE_DX;
			rigoreSegnato(Carta.valueOf(nomeCarta), cartaGiocata);
		}
	}

	public void initialize(URL arg0, ResourceBundle arg1)
	{	
		if(!(codicePartita == null)) 
		{
			try
			{
				leggiTurno();
				partita = (Partita) g.getGara(codicePartita);
				mazzo = partita.getMazzo();
				players = partita.getGiocatori();
				if(turno.equals("a"))
				{
					//visualizzare pallone ma non portiere
					imgPallone.setVisible(true);
					imgPortiere.setVisible(false);
				}
				else
				{
					//visualizzare portiere ma non pallone
					imgPallone.setVisible(false);
					imgPortiere.setVisible(true);
				}
			}
			catch(IOException e)
			{
				System.out.println(e.getMessage());
			}
		}
	}
	
	private void rigoreSegnato(Carta rigore, Carta portiere) {
		if(rigore.getDirezione().equals(portiere.getDirezione())) {
			players[posizioneGiocatoreAttaccante].aggiungiGoal();
		}
	}
	
	private void leggiTurno() throws IOException
	{
		String currentDirectory = System.getProperty("user.dir");
		String relativePath = "src/partite/"+codicePartita+"/turno.txt";
		String absolutePath = currentDirectory + File.separator + relativePath;
		File f = new File(absolutePath);
		Scanner scan = new Scanner(f);
		turno = scan.nextLine();
		posizioneGiocatoreAttaccante = scan.nextInt();
		posizioneGiocatoreDifensore = scan.nextInt();
		if(turno.equals("d"))
		{
			nomeCarta = scan.next();
		}
		scan.close();
	}
	
	private void salvaTurno() throws IOException{
		String currentDirectory = System.getProperty("user.dir");
		String relativePath = "src/partite/"+codicePartita+"/turno.txt";
		String absolutePath = currentDirectory + File.separator + relativePath;

		PrintWriter fw = new PrintWriter(absolutePath);
		if(turno.equals("a")) 
		{
			fw.println("d");
			fw.println(posizioneGiocatoreAttaccante);
			fw.println(posizioneGiocatoreDifensore);
			fw.println(cartaGiocata.name());
		}else 
		{
			fw.println("a");
			if((players.length-1) != posizioneGiocatoreAttaccante)
				fw.println(posizioneGiocatoreAttaccante+1);
			else
				fw.println(0);

			if((players.length-1) != posizioneGiocatoreDifensore)
				fw.println(posizioneGiocatoreDifensore+1);
			else
				fw.println(0);
		}
		fw.close();
	}
}