package application;

import javafx.fxml.FXML;
import javafx.scene.input.MouseEvent;

public class FormModalitaAdminMenuController {

	// Event Listener on Button.onMouseClicked
	@FXML
	public void btnCreaPartita(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onMouseClicked
	@FXML
	public void btnCreaTorneo(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onMouseClicked
	@FXML
	public void btnLogout(MouseEvent event) {
		// TODO Autogenerated
	}
}