package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.TextField;

import javafx.scene.control.ToggleGroup;
import javafx.scene.control.Alert.AlertType;

import java.io.IOException;

import javafx.event.ActionEvent;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Modality;
import javafx.stage.Stage;
import javafx.scene.control.Alert;
import javafx.scene.control.RadioButton;
import classi.Alert_cambiaForm;
public class FormCreaTorneoController {
	@FXML
	private AnchorPane rdbGiocatori4;
	@FXML
	private TextField txtCodice;
	@FXML
	private RadioButton rdbGiocatori2;
	@FXML
	private ToggleGroup numGiocatori;
	@FXML
	private RadioButton rdbGiocatori8;
	@FXML
	private RadioButton rdbGiocatori16;
	Alert_cambiaForm alert = new Alert_cambiaForm();
	// Event Listener on Button.onAction
	@FXML
	public void btnAvanti(ActionEvent event) {
		// TODO Autogenerated
	}
	public void btnVaiIndietro2(MouseEvent event) throws IOException
	{
		alert.passaAlForm("/application/FormModalitaAdminMenu.fxml",event);
	}
}
