package application;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class FormTabelloneTorneoController {
	@FXML
	private Label lblQuarto1;

	// Event Listener on Button.onAction
	@FXML
	public void btnAvviaPartita(ActionEvent event)
	{
		// TODO Autogenerated
	}
}
