package application;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

import javafx.scene.image.ImageView;

public class FormRigoreController {
	@FXML
	private ImageView imgPortiere;
	@FXML
	private ImageView imgPallone;

	// Event Listener on Button.onAction
	@FXML
	public void btnSinistra(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void btnCentro(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void btnDestra(ActionEvent event) {
		// TODO Autogenerated
	}
}
