package application;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

public class FormModalitaGiocatoreController
{

	// Event Listener on Button.onAction
	@FXML
	public void btnTornaFormPrincipale(ActionEvent event) 
	{
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void btnPartitaSingola(ActionEvent event) 
	{
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void btnTorneo(ActionEvent event) 
	{
		// TODO Autogenerated
	}
}
