package application;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import java.io.IOException;
import javafx.event.ActionEvent;
import javafx.stage.Stage;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.Node;

public class FormPrincipaleController 
{
	private Stage stage;
	private Scene scene;
	private Parent root;
	public void passaAlForm(ActionEvent event, String form) throws IOException {
		root = FXMLLoader.load(getClass().getResource(form));
	    stage = (Stage)((Node)event.getSource()).getScene().getWindow();
	    scene = new Scene(root);
	    stage.setScene(scene);
	    stage.show();
	}
	// Event Listener on Button.onAction
	@FXML
	public void btnVisualizzaLeaderboard(ActionEvent event)
	{
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void btnModalitaAmministratore(ActionEvent event) throws IOException
	{
		passaAlForm(event,"FormModalitaAmministratore.fxml");
	}
	// Event Listener on Button.onAction
	@FXML
	public void btnModalitaGiocatore(ActionEvent event) throws IOException 
	{
		passaAlForm(event,"FormModalitaGiocatore.fxml");
	}
}