package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class provaFormController {
	@FXML
	private TextField txtParola;
	@FXML
	private Button btnSalva;

	// Event Listener on Button[#btnSalva].onAction
	@FXML
	public void btnSalva(ActionEvent event) {
		// TODO Autogenerated
		
	}
}
